### ISSUE TITLE
generators.py ReshapeGenerator error

### ISSUE THREAD

**Issue by chtsao8** [jerryz123/onnx-halide#3]
Seems like there's a problem in the ReshapeGenerator under generators.py.

`Traceback (most recent call last):
  File "onnx_to_halide.py", line 5, in <module>
    prepared = backend.prepare(model)
  File "/home/charles/Documents/Onnx/onnx-halide/onnx_halide/backend.py", line 44, in prepare
    return HalideBackendRep(model)
  File "/home/charles/Documents/Onnx/onnx-halide/onnx_halide/backend_rep.py", line 41, in __init__
    self.generate_csrc(model)
  File "/home/charles/Documents/Onnx/onnx-halide/onnx_halide/backend_rep.py", line 159, in generate_csrc
    self.funcs, self.init_data))
  File "/home/charles/Documents/Onnx/onnx-halide/onnx_halide/generators.py", line 111, in __init__
    self.infer_shapes()
  File "/home/charles/Documents/Onnx/onnx-halide/onnx_halide/generators.py", line 1533, in infer_shapes
    self.op0.set_shape(tuple(map(int, self.ip1.data)))
AttributeError: 'HalideObj' object has no attribute 'data'
`

**Comment by jerryz123** [comment]
This is because this framework only supports reshaping when the output shape is statically known. That is, the shape array has a data field associated with it in the onnx description file.

**Comment by chtsao8** [comment]
Got it, thank you!
